### ISSUE TITLE
Add JWT Authentication

### ISSUE THREAD

**Issue by roseMunyiri** [roseMunyiri/Project-Planner#2]
Description:
We need to implement JSON Web Token (JWT) authentication in our application to enhance security and user authentication. a.

Objective:
The goal is to integrate JWT authentication into the application's authentication system, allowing users to securely authenticate and access protected resources.

Requirements:

Implement JWT authentication mechanism using libraries or frameworks compatible with our tech stack.
Provide endpoints for user registration, login, token generation, and token verification.
Securely store user credentials and validate them during authentication.
Ensure that JWT tokens are properly validated and expire after a specified period.
Handle token refresh mechanism to extend token validity without requiring users to re-authenticate frequently.

**Comment by Boy-Alone** [comment]
All is fine, will go on and test the JWT authentication. if all is fine will go with it
